Cleared deprecation error ROS 2 Galactic
Cleared error:
in generate_launch_description
    Node(
TypeError: __init__() missing 1 required keyword-only argument: 'executable'